# Generated by Django 6.0.1 on 2026-01-21 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_users_managers_users_date_joined_users_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/original/')),
                ('signed_file', models.FileField(blank=True, null=True, upload_to='documents/signed/')),
                ('hash_value', models.CharField(blank=True, max_length=64, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
